"""
生成 LVGL8 txt 格式小字库 ui_font_thesis_about20.c
字符：毕业设计谢志坚（关于页手表型号与软件/界面署名）
依赖：pip install freetype-py
字体：Windows 微软雅黑（与工程原 Cuyuan 接近）
"""

from __future__ import annotations

import os
import freetype  # type: ignore

# 与 ui_font_Cuyuan20 对齐，避免混排时行高跳变
LINE_HEIGHT = 22
BASE_LINE = 4
FONT_PX = 20
BPP = 4

# 去重且稳定顺序：按 Unicode 排序
CHARS = sorted(set("毕业设计谢志坚"))

FONT_PATHS = [
    r"C:\Windows\Fonts\msyh.ttc",
    r"C:\Windows\Fonts\msyhbd.ttc",
    r"C:\Windows\Fonts\simhei.ttf",
]


def load_face() -> freetype.Face:
    for p in FONT_PATHS:
        if os.path.isfile(p):
            return freetype.Face(p)
    raise SystemExit("No CJK font found; install msyh or simhei")


def pack_4bpp_gray(rows: list[bytes], w: int, h: int) -> bytes:
    """LVGL LV_FONT_FMT_TXT_PLAIN 4bpp：按行，每字节两个像素，高 4 位为左像素。"""
    out = bytearray()
    for y in range(h):
        row = rows[y]
        x = 0
        while x < w:
            left = row[x] if x < w else 0
            right = row[x + 1] if x + 1 < w else 0
            out.append((left << 4) | right)
            x += 2
    return bytes(out)


def render_glyph(face: freetype.Face, char: str) -> tuple[bytes, dict]:
    face.set_pixel_sizes(FONT_PX, FONT_PX)
    face.load_char(char, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
    slot = face.glyph
    bitmap = slot.bitmap
    w, h = bitmap.width, bitmap.rows
    left, top = slot.bitmap_left, slot.bitmap_top

    # 灰度 8bit -> 4bit (0=透明)
    rows: list[bytes] = []
    buf = bytes(bitmap.buffer)
    pitch = bitmap.pitch
    for y in range(h):
        row = bytearray(w)
        for x in range(w):
            v = buf[y * pitch + x] if pitch >= w else buf[y * w + x]
            row[x] = min(15, v >> 4)
        rows.append(bytes(row))

    data = pack_4bpp_gray(rows, w, h)
    # ofs_y：与 Cuyuan20 常见中文 ofs_y≈-(box_h - bitmap_top) 同量级
    ofs_y = top - h
    adv_px = max(1, int(round(slot.advance.x / 64.0)))
    adv_w = adv_px * 16

    meta = {
        "adv_w": adv_w,
        "box_w": w,
        "box_h": h,
        "ofs_x": left,
        "ofs_y": ofs_y,
    }
    return data, meta


def main() -> None:
    face = load_face()
    glyphs: list[tuple[str, int, bytes, dict]] = []
    all_bitmap = bytearray()
    for ch in CHARS:
        cp = ord(ch)
        blob, meta = render_glyph(face, ch)
        idx = len(all_bitmap)
        all_bitmap.extend(blob)
        glyphs.append((ch, cp, idx, meta))

    # SPARSE_TINY cmap
    cps = sorted(ord(c) for c in CHARS)
    range_start = min(cps)
    rcp_list = sorted([cp - range_start for cp in cps])
    range_length = max(rcp_list) + 1

    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_ui_font_thesis_about20.py — 勿手改 */")
    lines.append("")
    lines.append('#include "ui.h"')
    lines.append("")
    lines.append("#ifndef UI_FONT_THESIS_ABOUT20")
    lines.append("#define UI_FONT_THESIS_ABOUT20 1")
    lines.append("#endif")
    lines.append("")
    lines.append("#if UI_FONT_THESIS_ABOUT20")
    lines.append("")
    lines.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")

    # 格式化 bitmap 为 C 数组
    b = bytes(all_bitmap)
    chunk = 12
    for i in range(0, len(b), chunk):
        part = ", ".join(f"0x{x:02X}" for x in b[i : i + chunk])
        lines.append(f"    {part},")
    lines.append("};")
    lines.append("")

    lines.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    lines.append(
        "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* reserved */"
    )
    for ch, cp, idx, meta in glyphs:
        lines.append(
            "    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d}, /* U+%04X %s */"
            % (
                idx,
                meta["adv_w"],
                meta["box_w"],
                meta["box_h"],
                meta["ofs_x"],
                meta["ofs_y"],
                cp,
                ch,
            )
        )
    lines.append("};")
    lines.append("")

    ulist = ", ".join(f"0x{x:04X}" for x in rcp_list)
    lines.append(f"static const uint16_t unicode_list[] = {{{ulist}}};")
    lines.append("")
    lines.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    lines.append("    {")
    lines.append(f"        .range_start = {range_start},")
    lines.append(f"        .range_length = {range_length},")
    lines.append("        .glyph_id_start = 1,")
    lines.append("        .unicode_list = unicode_list,")
    lines.append("        .glyph_id_ofs_list = NULL,")
    lines.append(f"        .list_length = {len(rcp_list)},")
    lines.append("        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY,")
    lines.append("    }")
    lines.append("};")
    lines.append("")
    lines.append("#if LV_VERSION_CHECK(8, 0, 0)")
    lines.append("static lv_font_fmt_txt_glyph_cache_t cache;")
    lines.append("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    lines.append("#else")
    lines.append("static lv_font_fmt_txt_dsc_t font_dsc = {")
    lines.append("#endif")
    lines.append("    .glyph_bitmap = glyph_bitmap,")
    lines.append("    .glyph_dsc = glyph_dsc,")
    lines.append("    .cmaps = cmaps,")
    lines.append("    .kern_dsc = NULL,")
    lines.append("    .kern_scale = 0,")
    lines.append("    .cmap_num = 1,")
    lines.append(f"    .bpp = {BPP},")
    lines.append("    .kern_classes = 0,")
    lines.append("    .bitmap_format = LV_FONT_FMT_TXT_PLAIN,")
    lines.append("#if LV_VERSION_CHECK(8, 0, 0)")
    lines.append("    .cache = &cache")
    lines.append("#endif")
    lines.append("};")
    lines.append("")
    lines.append("#if LV_VERSION_CHECK(8, 0, 0)")
    lines.append("const lv_font_t ui_font_thesis_about20 = {")
    lines.append("#else")
    lines.append("lv_font_t ui_font_thesis_about20 = {")
    lines.append("#endif")
    lines.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    lines.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    lines.append(f"    .line_height = {LINE_HEIGHT},")
    lines.append(f"    .base_line = {BASE_LINE},")
    lines.append("#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)")
    lines.append("    .subpx = LV_FONT_SUBPX_NONE,")
    lines.append("#endif")
    lines.append("#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8")
    lines.append("    .underline_position = -4,")
    lines.append("    .underline_thickness = 1,")
    lines.append("#endif")
    lines.append("    .dsc = &font_dsc")
    lines.append("};")
    lines.append("")
    lines.append("#endif")

    out_path = os.path.join(
        os.path.dirname(__file__), "..", "USER", "GUI_App", "Fonts", "ui_font_thesis_about20.c"
    )
    out_path = os.path.normpath(out_path)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote", out_path, "glyphs", len(glyphs))


if __name__ == "__main__":
    main()
